Repository cms-analysis/HiggsAnalysis-CombinedLimit, pull requests merged in 2021-11, with the labels that each got.

#701 text2workspace: create discrete parameter set when no other systematics are present
  python/ModelTools.py
Labels: port to 112x

#695 Port to 112x comb2021
  bin/PerfTest.cpp
  interface/AtlasPdfs.h
  interface/CMSHggFormula.h
  interface/CMSHistFunc.h
  interface/CMSHistSum.h
  interface/RooCheapProduct.h
  interface/SimpleProdPdf.h
  interface/VerticalInterpPdf.h
  python/DatacardParser.py
  python/ShapeTools.py
  src/AtlasPdfs.cxx
  src/CMSHggFormula.cc
  src/CMSHistSum.cc
  src/CachingNLL.cc
  src/Combine.cc
  src/SimpleProdPdf.cc
  src/VerticalInterpPdf.cc
  src/classes.h
  src/classes_def.xml
Labels: safe to test, LHC Comb

#705 HMuMu pdfs
  interface/HMuMuRooPdfs.h
  src/HMuMuRooPdfs.cc
  src/classes.h
  src/classes_def.xml
Labels: CMS Comb

#706 HMuMu pdfs
  interface/HMuMuRooPdfs.h
  src/HMuMuRooPdfs.cc
  src/classes.h
  src/classes_def.xml
Labels: LHC Comb
