Repository cms-analysis/HiggsAnalysis-CombinedLimit, pull requests merged in 2022-08, with the labels that each got.

#777 112x: fix rateParameters ranges
  python/ModelTools.py
Labels: bug, port to 112x-comb2022

#780 port of #777 to 112x-comb2021
  python/ModelTools.py
Labels: safe to test

#781 Also open cards in text mode for gzip in combineCards.py
  scripts/combineCards.py
Labels: safe to test, port to 112x-comb2022

#776 ROOT 6.26 compatibility for 112x branch
  .github/workflows/ci.yml
  python/HiggsBenchmarkModels/VectorsAndFermionsModels.py
  python/HiggsCouplingsLOSM.py
  python/HiggsCouplings_ICHEP12.py
  python/LHCHCGModels.py
  python/ModelTools.py
  python/QuadraticScaling.py
  python/SMHiggsBuilder.py
  python/STXStoEFTModel.py
  python/ShapeTools.py
  src/AtlasPdfs.cxx
  src/CascadeMinimizer.cc
  src/RooRealFlooredSumPdf.cc
  src/ToyMCSamplerOpt.cc
  src/VerticalInterpPdf.cc
  test/rVrFLikelihoodScan.py
Labels: safe to test, port to 112x-comb2022

#784 Fix gcc compiler warnings
  src/BayesianToyMC.cc
  src/CascadeMinimizer.cc
  src/HybridNew.cc
  src/MultiDimFit.cc
  src/th1fmorph.cc
Labels: safe to test

#785 Remove rVrFLikelihood class and related test script
  interface/rVrFLikelihood.h
  src/classes.h
  src/classes_def.xml
  src/rVrFLikelihood.cc
  test/rVrFLikelihoodScan.py
Labels: safe to test

#787 Speed up datacard parsing
  python/DatacardParser.py
Labels: safe to test
