Repository cms-analysis/HiggsAnalysis-CombinedLimit, pull requests merged in 2022-04, with the labels that each got.

#655 Make floors in vertical pdf interpolator configurable
  interface/VerticalInterpPdf.h
  src/VerticalInterpPdf.cc
Labels: port to 112x

#733 102x port683
  interface/CMSHistFunc.h
  interface/CMSHistSum.h
  python/DatacardParser.py
  python/ShapeTools.py
  src/CMSHistSum.cc
  src/CachingNLL.cc
  src/Combine.cc
  src/classes.h
  src/classes_def.xml
  test/printWorkspaceNormalisations.py
Labels: port to 112x

#734 Port of 689
  interface/ProcessNormalization.h
  src/ProcessNormalization.cc
Labels: port to 112x

#735 fix remove multipdf option in systAnalyzer
  test/systematicsAnalyzer.py
Labels: port to 112x

#738 102x port of 664
  interface/CMSHggFormula.h
  interface/RooCheapProduct.h
  src/CMSHggFormula.cc
  src/classes.h
  src/classes_def.xml
Labels: port to 112x

#739 102x port 661
  python/DatacardParser.py
  python/ShapeTools.py
Labels: port to 112x

#749 Port 737 to 112x
  bin/BuildFile.xml
  bin/PerfTest.cpp
  interface/SimpleProdPdf.h
  interface/VerticalInterpPdf.h
  python/ShapeTools.py
  src/SimpleProdPdf.cc
  src/VerticalInterpPdf.cc
  src/classes.h
  src/classes_def.xml
Labels: safe to test

#743 PR 646
  src/FitDiagnostics.cc
Labels: safe to test, port to 112x

#742 Address rare case of NaN test statistics for AD GoF
  docs/part3/commonstatsmethods.md
  src/GoodnessOfFit.cc
Labels: port to 112x

#545 Addition of 2D RooParametricHist class
  interface/RooParametricHist2D.h
  python/ShapeTools.py
  src/RooParametricHist.cxx
  src/RooParametricHist2D.cxx
  src/classes.h
  src/classes_def.xml
Labels: safe to test

#548 Read shapes in from pandas dataframe
  data/tutorials/shapes/simple-shapes-df.txt
  data/tutorials/shapes/simple-shapes-df_input.csv
  docs/part2/settinguptheanalysis.md
  python/DataFrameWrapper.py
  python/ShapeTools.py
Labels: safe to test

#756 Cherry-pick #548 merge into 112x
  data/tutorials/shapes/simple-shapes-df.txt
  data/tutorials/shapes/simple-shapes-df_input.csv
  docs/part2/settinguptheanalysis.md
  python/DataFrameWrapper.py
  python/ShapeTools.py
Labels: safe to test

#755 Cherry-pick #545 merge into 112x
  interface/RooParametricHist2D.h
  python/ShapeTools.py
  src/RooParametricHist.cxx
  src/RooParametricHist2D.cxx
  src/classes.h
  src/classes_def.xml
Labels: safe to test

#758 Merge any remaining 102x items into 112x
  .github/workflows/docs.yml
  .github/workflows/port_to_branch.yml
  .travis.yml
  docs/index.md
  docs/part2/settinguptheanalysis.md
  docs/part3/commonstatsmethods.md
  docs/part3/debugging.md
  docs/part3/images/breakdown.png
  docs/part3/nonstandard.md
  docs/part3/runningthetool.md
  docs/part4/usefullinks.md
  docs/part5/longexercise.md
  mkdocs.yml
  python/Datacard.py
  python/LHCHCGModels.py
  python/NuisanceModifier.py
  python/SingleTopModels.py
  python/calculate_pulls.py
  src/CMSHistFunc.cc
  src/CachingNLL.cc
  src/Combine.cc
  src/FitDiagnostics.cc
  src/FitterAlgoBase.cc
  src/RooMultiPdf.cxx
  test/printAllCorrelations.py
  test/systematicsAnalyzer.py
Labels: safe to test
